//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

// `Eq` intentionally omitted: `weight` is `f64`, which is not `Eq`.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "branches")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub weight: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_json: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::branch_o2m_values::Entity")]
    BranchO2mValues,
    #[sea_orm(has_many = "super::branch_o2o_values::Entity")]
    BranchO2oValues,
    #[sea_orm(has_many = "super::branch_references::Entity")]
    BranchReferences,
    #[sea_orm(has_many = "super::usage_history::Entity")]
    UsageHistory,
}

impl Related<super::branch_o2m_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BranchO2mValues.def()
    }
}

impl Related<super::branch_o2o_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BranchO2oValues.def()
    }
}

impl Related<super::branch_references::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BranchReferences.def()
    }
}

impl Related<super::usage_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsageHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
