//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "frame_slot_o2m_values")]
pub struct Model {
    // The table has no DB-level primary key (DRAFT §16); declare a composite
    // key over all columns so SeaORM can treat it as an entity.
    #[sea_orm(primary_key, auto_increment = false)]
    pub slot_id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub mode: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub name: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::frame_slots::Entity",
        from = "Column::SlotId",
        to = "super::frame_slots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FrameSlots,
}

impl Related<super::frame_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FrameSlots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
