//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "frame_slots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub frame_id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub under_path: Option<String>,
    pub count: i32,
    pub avoid_recent: i32,
    pub weighted: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_suggest_json: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::frame_slot_o2m_values::Entity")]
    FrameSlotO2mValues,
    #[sea_orm(has_many = "super::frame_slot_o2o_values::Entity")]
    FrameSlotO2oValues,
    #[sea_orm(
        belongs_to = "super::frames::Entity",
        from = "Column::FrameId",
        to = "super::frames::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Frames,
}

impl Related<super::frame_slot_o2m_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FrameSlotO2mValues.def()
    }
}

impl Related<super::frame_slot_o2o_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FrameSlotO2oValues.def()
    }
}

impl Related<super::frames::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Frames.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
