//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod branch_o2m_values;
pub mod branch_o2o_values;
pub mod branch_references;
pub mod branches;
pub mod frame_slot_o2m_values;
pub mod frame_slot_o2o_values;
pub mod frame_slots;
pub mod frames;
pub mod selection_packets;
pub mod usage_history;
